name: pnpm-verify
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-version:
        type: string
        required: false
        default: "[18, 20]"
      pnpm-version:
        type: string
        required: false
        default: 9.0.6
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      artifact_paths:
        type: string
        required: false
jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        node-version: ${{ fromJson(inputs.node-version) }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ inputs.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Install Dependencies
        run: pnpm install

      - name: Verify
        run: pnpm verify
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 20
        with:
          path: ${{ inputs.artifact_paths }}